SELECT *
FROM (
    SELECT c.CAR_ID, c.CAR_TYPE, FLOOR(30*(100-p.DISCOUNT_RATE)/100*c.DAILY_FEE) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR c 
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE
    WHERE c.CAR_TYPE IN ('세단', 'SUV') 
        AND p.DURATION_TYPE = '30일 이상'
        AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
            WHERE h.CAR_ID = c.CAR_ID
            AND h.START_DATE <= '2022-11-30'AND h.END_DATE >= '2022-11-01'
        )
    ) AS sub
WHERE sub.FEE >= 500000 AND sub.FEE < 2000000
ORDER BY sub.FEE DESC, sub.CAR_TYPE ASC, sub.CAR_ID DESC;
