WITH RECURSIVE hours AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM hours
    WHERE HOUR < 23
)
SELECT h.HOUR AS `HOUR`, IFNULL(COUNT(a.datetime), 0) AS `COUNT`
FROM hours h
LEFT JOIN animal_outs a ON h.HOUR = HOUR(a.datetime)
GROUP BY h.HOUR
ORDER BY h.HOUR;
