WITH RECURSIVE HOUR AS(
    SELECT 0 AS N
    UNION ALL
    SELECT N + 1
    FROM HOUR
    WHERE N < 23
)

SELECT H.N, COUNT(O.DATETIME) AS COUNT
FROM ANIMAL_OUTS O
RIGHT JOIN HOUR H
ON HOUR(O.DATETIME) = H.N
GROUP BY H.N
